import React, { useState } from 'react';
import { HeliConfig } from '../types/blackbox';
import { useTheme } from '../context/ThemeContext';
import { Calculator, Copy, Check, Sliders, Zap } from 'lucide-react';

interface HarmonicsTuningAdvisorProps {
  config: HeliConfig;
  onConfigChange: (newConfig: HeliConfig) => void;
  detectedRpm?: number;
}

export const HarmonicsTuningAdvisor: React.FC<HarmonicsTuningAdvisorProps> = ({
  config,
  onConfigChange,
  detectedRpm,
}) => {
  const { theme } = useTheme();
  const isDark = theme === 'dark';
  const [copied, setCopied] = useState(false);

  // Derived harmonic frequencies
  const mainRpm = config.mainRpm || 2100;
  const main1P = mainRpm / 60;
  const main2P = main1P * config.bladeCount;
  const tail1P = main1P * config.tailGearRatio;
  const gearRatio = config.mainGearTeeth / config.motorPinionTeeth;
  const motor1P = main1P * gearRatio;

  const toFraction = (value: number, maxDenominator: number = 1000): [number, number] => {
    let bestN = 1;
    let bestD = 1;
    let bestError = Math.abs(value - 1);

    for (let d = 1; d <= maxDenominator; d++) {
      const n = Math.round(value * d);
      const error = Math.abs(value - n / d);
      if (error < bestError) {
        bestError = error;
        bestN = n;
        bestD = d;
      }
    }

    return [bestN, bestD];
  };

  const [tailGearNum, tailGearDen] = toFraction(config.tailGearRatio);

  // Recommended Rotorflight CLI settings
  const recommendedCli = `# Rotorflight Recommended Filter & Notch Settings
# Generated by Rotorflight Blackbox Vibration Analyzer
# Target Headspeed: ${Math.round(mainRpm)} RPM

# Gear Ratios (numerator,denominator)
set main_rotor_gear_ratio = ${config.mainGearTeeth},${config.motorPinionTeeth}
set tail_rotor_gear_ratio = ${tailGearNum},${tailGearDen}

# RPM Notch Filter
# Preset: 0=Off, 1=Low Vibration, 2=Typical Vibration, 3=High Vibration
set gyro_rpm_notch_preset = 2
set gyro_rpm_notch_min_hz = ${Math.round(main1P * 0.5)}

# Dynamic Notch Filter
set dyn_notch_count = 3
set dyn_notch_q = 60
set dyn_notch_min_hz = ${Math.max(10, Math.round(main1P * 0.85))}
set dyn_notch_max_hz = ${Math.min(500, Math.round(tail1P * 1.6))}

# Gyro Lowpass Cutoff
set gyro_lpf1_static_hz = ${Math.round(Math.min(250, tail1P * 1.3))}
set gyro_lpf1_dyn_min_hz = ${Math.round(main2P * 1.2)}
set gyro_lpf1_dyn_max_hz = ${Math.round(tail1P * 1.5)}

save`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(recommendedCli);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={`rounded-2xl border p-4 sm:p-5 shadow-sm flex flex-col gap-4 transition-colors ${
      isDark ? 'bg-slate-900/90 border-slate-800' : 'bg-white border-slate-200'
    }`}>
      {/* Header */}
      <div className={`flex flex-wrap items-center justify-between gap-2 pb-3 border-b ${
        isDark ? 'border-slate-800' : 'border-slate-100'
      }`}>
        <div className="flex items-center gap-2.5">
          <div className={`p-2 rounded-xl border ${
            isDark ? 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20' : 'bg-cyan-50 text-cyan-700 border-cyan-200'
          }`}>
            <Calculator className="w-5 h-5" />
          </div>
          <div>
            <h3 className={`text-base font-semibold ${isDark ? 'text-white' : 'text-slate-900'}`}>
              기체 기어비 & RPM 고조파 계산기 (Harmonic Calculator)
            </h3>
            <p className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
              헬리콥터 기어비 및 로터 회전수에 따른 주파수를 자동 계산하여 Rotorflight 필터 최적값을 생성합니다.
            </p>
          </div>
        </div>

        {detectedRpm && (
          <button
            onClick={() => onConfigChange({ ...config, mainRpm: Math.round(detectedRpm) })}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl border text-xs font-medium transition cursor-pointer ${
              isDark
                ? 'bg-cyan-950/60 hover:bg-cyan-900/60 border-cyan-800 text-cyan-300'
                : 'bg-cyan-50 hover:bg-cyan-100 border-cyan-300 text-cyan-800 shadow-xs'
            }`}
          >
            <Zap className={`w-3.5 h-3.5 ${isDark ? 'text-cyan-400' : 'text-cyan-600'}`} />
            <span>블랙박스 감지 RPM ({Math.round(detectedRpm)} RPM) 적용</span>
          </button>
        )}
      </div>

      {/* Input Parameters Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {/* Main RPM */}
        <div className={`p-3 rounded-xl border flex flex-col gap-1.5 ${
          isDark ? 'bg-slate-950/60 border-slate-800' : 'bg-slate-50 border-slate-200'
        }`}>
          <label className={`text-xs font-medium ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>헤드스피드 (RPM)</label>
          <input
            type="number"
            value={config.mainRpm}
            onChange={e => onConfigChange({ ...config, mainRpm: Number(e.target.value) })}
            className={`w-full border rounded-lg px-2.5 py-1.5 text-sm font-mono focus:outline-none focus:border-cyan-500 ${
              isDark ? 'bg-slate-900 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'
            }`}
            min="1000"
            max="4000"
            step="50"
          />
        </div>

        {/* Tail Gear Ratio */}
        <div className={`p-3 rounded-xl border flex flex-col gap-1.5 ${
          isDark ? 'bg-slate-950/60 border-slate-800' : 'bg-slate-50 border-slate-200'
        }`}>
          <label className={`text-xs font-medium ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>테일 기어비 (Tail Ratio)</label>
          <input
            type="number"
            value={config.tailGearRatio}
            onChange={e => onConfigChange({ ...config, tailGearRatio: Number(e.target.value) })}
            className={`w-full border rounded-lg px-2.5 py-1.5 text-sm font-mono focus:outline-none focus:border-cyan-500 ${
              isDark ? 'bg-slate-900 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'
            }`}
            min="3.0"
            max="6.0"
            step="0.05"
          />
        </div>

        {/* Main Gear / Pinion Teeth */}
        <div className={`p-3 rounded-xl border flex flex-col gap-1.5 ${
          isDark ? 'bg-slate-950/60 border-slate-800' : 'bg-slate-50 border-slate-200'
        }`}>
          <label className={`text-xs font-medium ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>메인 / 피니언 기어비</label>
          <div className="flex items-center gap-1">
            <input
              type="number"
              value={config.mainGearTeeth}
              onChange={e => onConfigChange({ ...config, mainGearTeeth: Number(e.target.value) })}
              className={`w-1/2 border rounded-lg px-2 py-1.5 text-xs font-mono text-center focus:outline-none focus:border-cyan-500 ${
                isDark ? 'bg-slate-900 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'
              }`}
              title="메인 기어 잇수 (Main Teeth)"
            />
            <span className={isDark ? 'text-slate-500' : 'text-slate-400'}>:</span>
            <input
              type="number"
              value={config.motorPinionTeeth}
              onChange={e => onConfigChange({ ...config, motorPinionTeeth: Number(e.target.value) })}
              className={`w-1/2 border rounded-lg px-2 py-1.5 text-xs font-mono text-center focus:outline-none focus:border-cyan-500 ${
                isDark ? 'bg-slate-900 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'
              }`}
              title="피니언 기어 잇수 (Pinion Teeth)"
            />
          </div>
        </div>

        {/* Blade Count */}
        <div className={`p-3 rounded-xl border flex flex-col gap-1.5 ${
          isDark ? 'bg-slate-950/60 border-slate-800' : 'bg-slate-50 border-slate-200'
        }`}>
          <label className={`text-xs font-medium ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>메인 블레이드 수</label>
          <select
            value={config.bladeCount}
            onChange={e => onConfigChange({ ...config, bladeCount: Number(e.target.value) })}
            className={`w-full border rounded-lg px-2.5 py-1.5 text-sm font-mono focus:outline-none focus:border-cyan-500 ${
              isDark ? 'bg-slate-900 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'
            }`}
          >
            <option value="2">2-블레이드 (일반 FBL)</option>
            <option value="3">3-블레이드 (트라이블레이드)</option>
            <option value="4">4-블레이드 (스케일 헤드)</option>
          </select>
        </div>
      </div>

      {/* Calculated Frequencies Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className={`p-3 rounded-xl border flex flex-col justify-between ${
          isDark ? 'bg-blue-950/20 border-blue-800/40' : 'bg-blue-50/70 border-blue-200'
        }`}>
          <span className={`text-xs font-medium ${isDark ? 'text-blue-300' : 'text-blue-800'}`}>1P 메인 로터</span>
          <div className="mt-1 flex items-baseline justify-between">
            <span className={`text-xl font-bold font-mono ${isDark ? 'text-blue-400' : 'text-blue-600'}`}>{main1P.toFixed(1)} Hz</span>
            <span className={`text-[10px] ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>1x Head RPM</span>
          </div>
          <span className={`text-[11px] mt-1 ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>블레이드 밸런스 / 스핀들 축</span>
        </div>

        <div className={`p-3 rounded-xl border flex flex-col justify-between ${
          isDark ? 'bg-purple-950/20 border-purple-800/40' : 'bg-purple-50/70 border-purple-200'
        }`}>
          <span className={`text-xs font-medium ${isDark ? 'text-purple-300' : 'text-purple-800'}`}>{config.bladeCount}P 블레이드 통과</span>
          <div className="mt-1 flex items-baseline justify-between">
            <span className={`text-xl font-bold font-mono ${isDark ? 'text-purple-400' : 'text-purple-600'}`}>{main2P.toFixed(1)} Hz</span>
            <span className={`text-[10px] ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>{config.bladeCount}x Head RPM</span>
          </div>
          <span className={`text-[11px] mt-1 ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>트래킹 차이 / 피치 로드</span>
        </div>

        <div className={`p-3 rounded-xl border flex flex-col justify-between ${
          isDark ? 'bg-amber-950/20 border-amber-800/40' : 'bg-amber-50/70 border-amber-200'
        }`}>
          <span className={`text-xs font-medium ${isDark ? 'text-amber-300' : 'text-amber-800'}`}>테일 로터 1P</span>
          <div className="mt-1 flex items-baseline justify-between">
            <span className={`text-xl font-bold font-mono ${isDark ? 'text-amber-400' : 'text-amber-600'}`}>{tail1P.toFixed(1)} Hz</span>
            <span className={`text-[10px] ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>{config.tailGearRatio}x Ratio</span>
          </div>
          <span className={`text-[11px] mt-1 ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>테일 밸런스 / 벨트 장력</span>
        </div>

        <div className={`p-3 rounded-xl border flex flex-col justify-between ${
          isDark ? 'bg-pink-950/20 border-pink-800/40' : 'bg-pink-50/70 border-pink-200'
        }`}>
          <span className={`text-xs font-medium ${isDark ? 'text-pink-300' : 'text-pink-800'}`}>모터 전기/샤프트 1P</span>
          <div className="mt-1 flex items-baseline justify-between">
            <span className={`text-xl font-bold font-mono ${isDark ? 'text-pink-400' : 'text-pink-600'}`}>{motor1P.toFixed(1)} Hz</span>
            <span className={`text-[10px] ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>비 {gearRatio.toFixed(2)}:1</span>
          </div>
          <span className={`text-[11px] mt-1 ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>모터 베어링 / 백래시</span>
        </div>
      </div>

      {/* Generated Rotorflight CLI Configuration */}
      <div className={`rounded-xl border p-3.5 flex flex-col gap-2 ${
        isDark ? 'bg-slate-950 border-slate-800' : 'bg-slate-50 border-slate-200'
      }`}>
        <div className="flex items-center justify-between">
          <span className={`text-xs font-semibold flex items-center gap-1.5 ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
            <Sliders className={`w-3.5 h-3.5 ${isDark ? 'text-cyan-400' : 'text-cyan-600'}`} />
            <span>Rotorflight CLI 설정 코드 (복사하여 CLI 탭에 붙여넣기)</span>
          </span>
          <button
            onClick={copyToClipboard}
            className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 text-xs font-bold transition shadow-xs cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-slate-950" /> : <Copy className="w-3.5 h-3.5 text-slate-950" />}
            <span>{copied ? '복사 완료!' : 'CLI 복사'}</span>
          </button>
        </div>

        <pre className={`p-3 rounded-lg border text-xs font-mono overflow-x-auto leading-relaxed max-h-44 ${
          isDark ? 'bg-slate-900 border-slate-800 text-slate-300' : 'bg-white border-slate-200 text-slate-800'
        }`}>
          {recommendedCli}
        </pre>
      </div>
    </div>
  );
};
